name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Required for ghcr.io

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Remove slashes from the github ref name
      run: echo "REF_NAME=${GITHUB_REF_NAME////-}" >> $GITHUB_ENV
    - name: Get the image tag
      run: echo "IMAGE_TAG=${{ github.event_name == 'pull_request' && format('pr-{0}-{1}', github.event.number, github.event.pull_request.head.sha) || format('{0}-{1}', env.REF_NAME, github.sha) }}" >> $GITHUB_ENV
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}

    - name: Build and push debug Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.dbg
        push: true
        tags: ghcr.io/${{ github.repository }}:dbg-${{ env.IMAGE_TAG }}
        build-args: |
          BASE_IMAGE=ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}
